version: '3.8'

services:
  postgres-gis:
    image: postgis/postgis:16-3.4
    container_name: my-postgis-container
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mycidaxdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  maycidax-api:
    container_name: mycidax-api-container
    build:
      context: .
      dockerfile: src/Backend/MyCidax.API/Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: "Host=postgres-gis;Port=5432;Database=mycidaxdb;Username=myuser;Password=mypassword"
    depends_on:
      - postgres-gis
    restart: unless-stopped

volumes:
  postgres_data:
